### ISSUE TITLE
User can get a random advice by clicking button

### ISSUE THREAD

**Issue by daniel-sungwon-lee** [daniel-sungwon-lee/ajax-project#2]
## ✅ Task List
- [x] create html/css
- [x] make function to swap views
- [x] swap views and get a random advice when the button is pressed
- [x] check for bugs
- [x] clean up code

**Comment by daniel-sungwon-lee** [comment]
- [ ]
