### ISSUE TITLE
User can get a random quote by clicking button

### ISSUE THREAD

**Issue by daniel-sungwon-lee** [daniel-sungwon-lee/ajax-project#3]
## ✅ Task List
- [x] Get random quote by clicking button
- [x] Add a Favorites button to add advice/quote
- [x] Add advice/quote to Favorites section
- [x] Check for bugs
- [x] Clean up code
