### ISSUE TITLE
User can get a random dad joke by clicking button

### ISSUE THREAD

**Issue by daniel-sungwon-lee** [daniel-sungwon-lee/ajax-project#4]
## ✅ Task List
- [x] Get a dad joke when user clicks on button
- [x] add joke if add button is pressed
- [x] clean up code
- [x] fix bugs
