### ISSUE TITLE
User can get a random activity by clicking button

### ISSUE THREAD

**Issue by daniel-sungwon-lee** [daniel-sungwon-lee/ajax-project#5]
## ✅ Task List
- [x] user can get random activity by clicking button
- [x] create new To-Do section
- [x] activity can be added to To-Do section when button is pressed
- [x] clean up code
- [x] fix bugs
