### ISSUE TITLE
User can add any data to their favorites/to-do list

### ISSUE THREAD

**Issue by daniel-sungwon-lee** [daniel-sungwon-lee/ajax-project#6]
- [x] create checkboxes to To-Do list
- [x] save the checked data
- [x] fix bugs
- [x] clean up code
